reboot:
  description: Choose miner device to reboot
  target:
    entity:
      integration: miner

restart_backend:
  description: Choose miner device to restart the mining process of
  target:
    entity:
      integration: miner
